server.port=9102

spring.application.name=eureka-server

# Eureka Server seul
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false

spring.cloud.config.import-check.enabled=false

# Évite la réplication vers un autre Eureka
eureka.server.maxThreadsForPeerReplication=0
