server.port=9001

# H2
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# data.sql
spring.datasource.sql-script-encoding=UTF-8
spring.jpa.defer-datasource-initialization=true

# Configuration externalisée
mes-configs.limitDeProduits=3
