server.port=9001

# Configurations H2
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.datasource.sql-script-encoding=UTF-8
spring.jpa.defer-datasource-initialization=true

# Configuration externalisée
mes-configs.limitDeProduits=4

# Actuator : exposer tous les endpoints
management.endpoints.web.exposure.include=*
